---

version: "3.9"

networks:
  ansible_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.56.0/24

services:
  node1:
    build: .
    container_name: node1
    hostname: node1
    networks:
      ansible_net:
        ipv4_address: 192.168.56.101
    ports:
      - "2222:22"

  node2:
    build: .
    container_name: node2
    hostname: node2
    networks:
      ansible_net:
        ipv4_address: 192.168.56.102
    ports:
      - "2223:22"
